[tool.poetry]
name = "so3lr-sf"
version = "0.0.1"
description = "SO3krates Universal Pairwise Force Field with Long Range Interactions (SO3LR) as a scoring function for binding affinity calculations"
authors = ["Hamza Ibrahim"]
license = "MIT"


[tool.poetry.dependencies]
python = ">=3.12,<4.0"
numpy = "*"
ase = "*"
h5py = "*"
rdkit = "^2025.03.6"
prolif = "^2.0.0"
tensorflow = "^2.20.0"
keras = "^3.11.3"
scipy = "^1.16.2"
pandas = "^2.3.2"
matplotlib = "^3.10.6"
protobuf = "^6.32.1"
typing-extensions = "^4.15.0"
jax = "0.5.3"
jaxtyping = "^0.3.2"
jaxlib = "==0.5.3"
mlff = { git = "https://github.com/hamzaibrahim21/mlff.git", branch = "v1.0-eda", optional = false }
so3lr = { git = "https://github.com/hamzaibrahim21/so3lr.git", branch = "main", optional = false }

[tool.poetry.group.test.dependencies]
pytest = "^8.0.0"
pytest-cov = "^6.0.0"
coverage = "^7.6.0"
coverage-badge = "^1.1.0"
pytest-xdist = "^3.6.0"
pytest-mock = "^3.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"